services:
  # Dashboard (central hub)
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    hostname: homepage
    restart: unless-stopped
    ports:
      - "3000:3000" # Web UI
    volumes:
      - ./homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - ./.env

  # Download managers (Torrent)
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    restart: unless-stopped
    volumes:
      - ${ARRPATH}qbittorrent/config:/config
      - ${ARRPATH}downloads:/downloads
    ports:
      - "8080:8080" # Web UI
      - "6881:6881" # TCP port for torrents
      - "6881:6881/udp" # UDP port for torrents
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    env_file:
      - ./.env

  # Indexers
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    restart: unless-stopped
    volumes:
      - ${ARRPATH}prowlarr/config:/config
      - ${ARRPATH}prowlarr/backup:/data/backup
      - ${ARRPATH}downloads:/downloads
    ports:
      - "9696:9696" # Web UI
    env_file:
      - ./.env

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    hostname: jackett
    restart: unless-stopped
    volumes:
      - ${ARRPATH}jackett/data:/config
      - ${ARRPATH}blackhole:/downloads
    ports:
      - "9117:9117" # Web UI
    env_file:
      - ./.env

  # Media management (Movies & TV)
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    restart: unless-stopped
    volumes:
      - ${ARRPATH}sonarr/config:/config
      - ${ARRPATH}sonarr/backup:/data/backup
      - ${ARRPATH}sonarr/tvshows:/data/tvshows
      - ${ARRPATH}downloads:/downloads
    ports:
      - "8989:8989" # Web UI
    env_file:
      - ./.env

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    restart: unless-stopped
    volumes:
      - ${ARRPATH}radarr/config:/config
      - ${ARRPATH}radarr/movies:/data/movies
      - ${ARRPATH}radarr/backup:/data/backup
      - ${ARRPATH}downloads:/downloads
    ports:
      - "7878:7878" # Web UI
    env_file:
      - ./.env

  # Media streaming servers
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    restart: unless-stopped
    volumes:
      - ${ARRPATH}jellyfin/config:/config
      - ${ARRPATH}radarr/movies:/data/movies
      - ${ARRPATH}sonarr/tvshows:/data/tvshows
    ports:
      - "8096:8096/tcp" # Web UI
      - "7359:7359/udp" # Auto-discovery
      - "1900:1900/udp" # DLNA/UPnP
    env_file:
      - ./.env

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    hostname: plex
    network_mode: host # Port will be 32400, open http://<host>:32400/web
    restart: unless-stopped
    environment:
      - VERSION=docker
      # If you want Plex to auto-claim, uncomment and set your token:
      # - PLEX_CLAIM=<TU_PLEX_CLAIM_TOKEN>
    volumes:
      - ${ARRPATH}plex/config:/config
      - ${ARRPATH}sonarr/tvshows:/data/tvshows
      - ${ARRPATH}radarr/movies:/data/movies
    env_file:
      - ./.env
